version: '3.8'
services:

  postgres:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=musicbox
      - POSTGRES_PASSWORD=musicbox
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: